// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvx56Wp3R5M4d0I1lwYc6fhgJy6dTFNPM',
    appId: '1:863692183597:android:0591105e8b1bb60b9b80a4',
    messagingSenderId: '863692183597',
    projectId: 'fuse-2-0',
    databaseURL: 'https://fuse-2-0.firebaseio.com',
    storageBucket: 'fuse-2-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1DHZQFPrNZo-dgm68PSaABIeGIc16nbY',
    appId: '1:863692183597:ios:91186a513b10fab59b80a4',
    messagingSenderId: '863692183597',
    projectId: 'fuse-2-0',
    databaseURL: 'https://fuse-2-0.firebaseio.com',
    storageBucket: 'fuse-2-0.appspot.com',
    androidClientId: '863692183597-0colm33bu1u8hbtacstdpv33pvdjsr8a.apps.googleusercontent.com',
    iosClientId: '863692183597-dj519lg1gf92k0d41a5pe94bio1k14v8.apps.googleusercontent.com',
    iosBundleId: 'io.fuse.fusecash',
  );
}
